// This file is automatically generated. Do not edit it directly.
// Aplikácia výhradne ťahá recepty a všetky dáta zo Supabase – žiadny iný backend.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Chýbajú Supabase premenné. Nastav VITE_SUPABASE_URL a VITE_SUPABASE_PUBLISHABLE_KEY v .env (lokálne) alebo v nastaveniach deployu (Vercel)."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});